print('Python Print Function')
print('C++ Print Funtion')
print('Java Print Function')
print('JavaScript Print Functádđsaion')
print('Ruby Print Functiassoaan')
print('co len nha ông bạn già')
print('Python Print Function')
print('C++ Print Funtion')
print('Java Print Function')
print('JavaScript Print Functádđsaion')
print('Ruby Print Functiassoaan')
print('co len nha ông bạn già')
print('Python Print Function')
print('C++ Print Funtion')
print('Java Print Function')
print('JavaScript Print Functádđsaion')
print('Ruby Print Functiassoaan')
print('co len nha ông bạn già')
