print('Python Print Function')
print('C++ Print Funtion')
print('Java Print Function')
print('JavaScript Print Functádđsaion')
print('Ruby Print Functiassoaaaaaaaaaaaan')
print('Go Print Function')
print('Swift Print Function')
print('Kotlin Print Function')